### ISSUE TITLE
Demo Application Crash on Windows 10 Run 

### ISSUE THREAD

**Issue by itssource** [godotneers/saving-loading-video#1]
![image](https://github.com/godotneers/saving-loading-video/assets/27980060/e80900a3-e507-4d4f-a855-d8603cdda6af)

No exact replication procedures, as I do not remember all the steps. But the gist of it was that I destroyed the top fish, let the sub take damage, each time hitting the Save button. Move the sub around, saved, crash happened around that point.

**Comment by derkork** [comment]
I can unfortunately not reproduce this. Also the the screenshot would indicate a problem during loading while you wrote that the problem occurred during saving.  It would really help if you could provide a list of steps to reproduce the issue. Also which branch are you running?

**Comment by itssource** [comment]
Yes, I did exclude the "Load" comment I meant to add. It was a combination of Save and Load use, while moving the player and shooting the projectiles, after destroying I believe the topmost enemy. I hit the buttons so many times in various order, and after game loop changes, I am not able to accurately give a replication procedure set of steps. It would seem a corner case issue that may not warrant further investigation. I'll close this issue based on that last point. (Godot Engine version is top-right of the embedded screen capture, above)
